rsyslog:
  build: /usr/src/docker/rsyslog
  volumes:
    - /tmp/syslogdev:/dev
  hostname: rsyslog

consul:
  image: progrium/consul
  ports:
    - "8500:8500"
    - "8300:8300"
    - "8300:8300/udp"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "53:53/udp"
  command: -server -bootstrap -advertise PUB_IP -syslog -ui-dir /ui
  hostname: consul
  links:
    - rsyslog
  environment:
    - SERVICE_8500_NAME=consul_web
    - SERVICE_53_NAME=consul_dns
  volumes:
    - /tmp/syslogdev/log:/dev/log

registrator:
  image: progrium/registrator
  command: consul://consul:8500
  links:
    - consul
    - rsyslog
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /tmp/syslogdev/log:/dev/log
  hostname: registrator


